name: Test

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
jobs:

  build:
    runs-on: Ubuntu-16.04
    strategy:
      matrix:
        Build: [0]
        Test: [0]
      fail-fast: false
    steps:
    - name: Run checkout@v2.3.4
      uses: actions/checkout@v2.3.4

    - name: Run
      run: |
        echo "done"
    - name: Test
      run: |
        rm -rf *
        echo "done"  
